"""empty message

Revision ID: 69378b4c1f61
Revises: 40d4a415c07d
Create Date: 2022-10-02 19:34:54.971551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69378b4c1f61'
down_revision = '40d4a415c07d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('question_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_column('answer', 'Question_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('Question_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'question', ['Question_id'], ['id'], ondelete='CASCADE')
    op.drop_column('answer', 'question_id')
    # ### end Alembic commands ###
